import { index, type RouteConfig, route } from '@react-router/dev/routes'

export default [
  index('routes/home.tsx'),
  route('login', 'routes/login.tsx'),
  route('login/mfa', 'routes/login.mfa.tsx'),
  route('logout', 'routes/logout.tsx'),
  route('verify-email', 'routes/verify-email.tsx'),
  route('forgot-password', 'routes/forgot-password.tsx'),
  route('reset-password', 'routes/reset-password.tsx'),
  route('account/mfa', 'routes/account-mfa.tsx'),
  route('api/passkey', 'routes/api.passkey.tsx'),
  route('api/reveal-token', 'routes/api.reveal-token.tsx'),
  route('sso/:orgId/start', 'routes/sso.start.tsx'),
  route('sso/:orgId/callback', 'routes/sso.callback.tsx'),
  route('saml/:orgId/start', 'routes/saml.start.tsx'),
  route('saml/:orgId/acs', 'routes/saml.acs.tsx'),
  route('oauth/:provider/start', 'routes/oauth.start.tsx'),
  route('oauth/:provider/callback', 'routes/oauth.callback.tsx'),
  route('dashboard/:workspaceId', 'routes/workspace.tsx', [
    index('routes/workspace.overview.tsx'),
    route('environments', 'routes/workspace.environments.tsx'),
    route('compare', 'routes/dashboard.compare.tsx'),
    route('audit', 'routes/dashboard.audit.tsx'),
    route('notifications', 'routes/dashboard.notifications.tsx'),
    route('env/:envId', 'routes/environment.tsx', [
      index('routes/environment._index.tsx'),
      route('config', 'routes/environment.config.tsx'),
      route('flags', 'routes/environment.flags.tsx'),
      route('secrets', 'routes/environment.secrets.tsx'),
      route('content', 'routes/environment.content.tsx'),
      route('keys', 'routes/environment.keys.tsx'),
    ]),
    route('env/:envId/pages/:key', 'routes/content-page.tsx'),
  ]),
  route('dashboard/:workspaceId/assistant', 'routes/assistant.tsx'),
  route('dashboard/:workspaceId/assistant/history', 'routes/assistant.history.tsx'),
  route('share', 'routes/share.tsx'),
  route('s/:id', 'routes/share.view.tsx'),
  route('invite/:id', 'routes/invite.tsx'),
  route('orgs/:orgId/members', 'routes/members.tsx'),
  route('orgs/:orgId/billing', 'routes/billing.tsx'),
  route('orgs/:orgId/domains', 'routes/domains.tsx'),
  route('orgs/:orgId/scim', 'routes/scim.tsx'),
  route('orgs/:orgId/sso', 'routes/sso-admin.tsx'),
  route('orgs/:orgId/saml', 'routes/saml-admin.tsx'),
] satisfies RouteConfig
