export type { Database, DatabaseConnection, Schema } from './client'
export { createDatabase } from './client'
export {
  type AuthenticatorRow,
  addOrgMember,
  confirmTotpCredential,
  consumeSamlAssertion,
  createAuthenticator,
  deleteTotpCredential,
  type EntitlementRow,
  getAccountByProvider,
  getAuthenticatorById,
  getAuthenticatorsByUser,
  getEntitlements,
  getMeterWatermark,
  getOrganizationIdBySlug,
  getSamlConnection,
  getScimTokenHash,
  getSsoConnection,
  getStripeCustomer,
  getTotpCredential,
  listOrgMembers,
  listStripeCustomers,
  listWorkspaceOrganizations,
  type MemberMutationError,
  type MemberRole,
  monthlyActiveUsersByOrg,
  type OrgMember,
  removeOrgMember,
  type SamlConnectionRow,
  type SsoConnectionRow,
  type StripeCustomerRow,
  setMeterWatermark,
  setScimTokenHash,
  type TotpCredentialRow,
  updateAuthenticatorCounter,
  updateOrgMemberRole,
  upsertEntitlements,
  upsertSamlConnection,
  upsertSsoConnection,
  upsertStripeCustomer,
  upsertTotpSecret,
} from './queries'
export * as schema from './schema'
export * from './schema'
