export type { Database, DatabaseConnection, Schema } from './client'
export { createDatabase } from './client'
export {
  type AuthenticatorRow,
  acceptInvitation,
  addOrgMember,
  confirmTotpCredential,
  consumeSamlAssertion,
  createAuthenticator,
  createInvitation,
  deleteTotpCredential,
  type EntitlementRow,
  getAccountByProvider,
  getAuthenticatorById,
  getAuthenticatorsByUser,
  getEntitlements,
  getInvitation,
  getMeterWatermark,
  getOrganizationIdBySlug,
  getSamlConnection,
  getScimTokenHash,
  getSsoConnection,
  getStripeCustomer,
  getTotpCredential,
  getUserEmail,
  type InvitationError,
  type InvitationRow,
  listOrgMembers,
  listPendingInvitations,
  listStripeCustomers,
  listWorkspaceOrganizations,
  type MemberMutationError,
  type MemberRole,
  monthlyActiveUsersByOrg,
  type OrgMember,
  removeOrgMember,
  revokeInvitation,
  type SamlConnectionRow,
  type SsoConnectionRow,
  type StripeCustomerRow,
  setMeterWatermark,
  setScimTokenHash,
  type TotpCredentialRow,
  updateAuthenticatorCounter,
  updateOrgMemberRole,
  upsertEntitlements,
  upsertSamlConnection,
  upsertSsoConnection,
  upsertStripeCustomer,
  upsertTotpSecret,
} from './queries'
export * as schema from './schema'
export * from './schema'
