// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/login/mfa": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/account/mfa": {
    params: {};
  };
  "/api/passkey": {
    params: {};
  };
  "/api/reveal-token": {
    params: {};
  };
  "/sso/:orgId/start": {
    params: {
      "orgId": string;
    };
  };
  "/sso/:orgId/callback": {
    params: {
      "orgId": string;
    };
  };
  "/saml/:orgId/start": {
    params: {
      "orgId": string;
    };
  };
  "/saml/:orgId/acs": {
    params: {
      "orgId": string;
    };
  };
  "/oauth/:provider/start": {
    params: {
      "provider": string;
    };
  };
  "/oauth/:provider/callback": {
    params: {
      "provider": string;
    };
  };
  "/dashboard/:workspaceId": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/environments": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/compare": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/audit": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/notifications": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId": {
    params: {
      "workspaceId": string;
      "envId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId/config": {
    params: {
      "workspaceId": string;
      "envId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId/flags": {
    params: {
      "workspaceId": string;
      "envId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId/secrets": {
    params: {
      "workspaceId": string;
      "envId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId/content": {
    params: {
      "workspaceId": string;
      "envId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId/keys": {
    params: {
      "workspaceId": string;
      "envId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId/pages/:key": {
    params: {
      "workspaceId": string;
      "envId": string;
      "key": string;
    };
  };
  "/dashboard/:workspaceId/assistant": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/assistant/history": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/assistant/ws-token": {
    params: {
      "workspaceId": string;
    };
  };
  "/share": {
    params: {};
  };
  "/s/:id": {
    params: {
      "id": string;
    };
  };
  "/invite/:id": {
    params: {
      "id": string;
    };
  };
  "/orgs/:orgId/members": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/billing": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/domains": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/scim": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/sso": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/saml": {
    params: {
      "orgId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/login/mfa" | "/logout" | "/verify-email" | "/forgot-password" | "/reset-password" | "/account/mfa" | "/api/passkey" | "/api/reveal-token" | "/sso/:orgId/start" | "/sso/:orgId/callback" | "/saml/:orgId/start" | "/saml/:orgId/acs" | "/oauth/:provider/start" | "/oauth/:provider/callback" | "/dashboard/:workspaceId" | "/dashboard/:workspaceId/environments" | "/dashboard/:workspaceId/compare" | "/dashboard/:workspaceId/audit" | "/dashboard/:workspaceId/notifications" | "/dashboard/:workspaceId/env/:envId" | "/dashboard/:workspaceId/env/:envId/config" | "/dashboard/:workspaceId/env/:envId/flags" | "/dashboard/:workspaceId/env/:envId/secrets" | "/dashboard/:workspaceId/env/:envId/content" | "/dashboard/:workspaceId/env/:envId/keys" | "/dashboard/:workspaceId/env/:envId/pages/:key" | "/dashboard/:workspaceId/assistant" | "/dashboard/:workspaceId/assistant/history" | "/dashboard/:workspaceId/assistant/ws-token" | "/share" | "/s/:id" | "/invite/:id" | "/orgs/:orgId/members" | "/orgs/:orgId/billing" | "/orgs/:orgId/domains" | "/orgs/:orgId/scim" | "/orgs/:orgId/sso" | "/orgs/:orgId/saml";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/login.mfa.tsx": {
    id: "routes/login.mfa";
    page: "/login/mfa";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/verify-email.tsx": {
    id: "routes/verify-email";
    page: "/verify-email";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/account-mfa.tsx": {
    id: "routes/account-mfa";
    page: "/account/mfa";
  };
  "routes/api.passkey.tsx": {
    id: "routes/api.passkey";
    page: "/api/passkey";
  };
  "routes/api.reveal-token.tsx": {
    id: "routes/api.reveal-token";
    page: "/api/reveal-token";
  };
  "routes/sso.start.tsx": {
    id: "routes/sso.start";
    page: "/sso/:orgId/start";
  };
  "routes/sso.callback.tsx": {
    id: "routes/sso.callback";
    page: "/sso/:orgId/callback";
  };
  "routes/saml.start.tsx": {
    id: "routes/saml.start";
    page: "/saml/:orgId/start";
  };
  "routes/saml.acs.tsx": {
    id: "routes/saml.acs";
    page: "/saml/:orgId/acs";
  };
  "routes/oauth.start.tsx": {
    id: "routes/oauth.start";
    page: "/oauth/:provider/start";
  };
  "routes/oauth.callback.tsx": {
    id: "routes/oauth.callback";
    page: "/oauth/:provider/callback";
  };
  "routes/workspace.tsx": {
    id: "routes/workspace";
    page: "/dashboard/:workspaceId" | "/dashboard/:workspaceId/environments" | "/dashboard/:workspaceId/compare" | "/dashboard/:workspaceId/audit" | "/dashboard/:workspaceId/notifications" | "/dashboard/:workspaceId/env/:envId" | "/dashboard/:workspaceId/env/:envId/config" | "/dashboard/:workspaceId/env/:envId/flags" | "/dashboard/:workspaceId/env/:envId/secrets" | "/dashboard/:workspaceId/env/:envId/content" | "/dashboard/:workspaceId/env/:envId/keys" | "/dashboard/:workspaceId/env/:envId/pages/:key";
  };
  "routes/workspace.overview.tsx": {
    id: "routes/workspace.overview";
    page: "/dashboard/:workspaceId";
  };
  "routes/workspace.environments.tsx": {
    id: "routes/workspace.environments";
    page: "/dashboard/:workspaceId/environments";
  };
  "routes/dashboard.compare.tsx": {
    id: "routes/dashboard.compare";
    page: "/dashboard/:workspaceId/compare";
  };
  "routes/dashboard.audit.tsx": {
    id: "routes/dashboard.audit";
    page: "/dashboard/:workspaceId/audit";
  };
  "routes/dashboard.notifications.tsx": {
    id: "routes/dashboard.notifications";
    page: "/dashboard/:workspaceId/notifications";
  };
  "routes/environment.tsx": {
    id: "routes/environment";
    page: "/dashboard/:workspaceId/env/:envId" | "/dashboard/:workspaceId/env/:envId/config" | "/dashboard/:workspaceId/env/:envId/flags" | "/dashboard/:workspaceId/env/:envId/secrets" | "/dashboard/:workspaceId/env/:envId/content" | "/dashboard/:workspaceId/env/:envId/keys";
  };
  "routes/environment._index.tsx": {
    id: "routes/environment._index";
    page: "/dashboard/:workspaceId/env/:envId";
  };
  "routes/environment.config.tsx": {
    id: "routes/environment.config";
    page: "/dashboard/:workspaceId/env/:envId/config";
  };
  "routes/environment.flags.tsx": {
    id: "routes/environment.flags";
    page: "/dashboard/:workspaceId/env/:envId/flags";
  };
  "routes/environment.secrets.tsx": {
    id: "routes/environment.secrets";
    page: "/dashboard/:workspaceId/env/:envId/secrets";
  };
  "routes/environment.content.tsx": {
    id: "routes/environment.content";
    page: "/dashboard/:workspaceId/env/:envId/content";
  };
  "routes/environment.keys.tsx": {
    id: "routes/environment.keys";
    page: "/dashboard/:workspaceId/env/:envId/keys";
  };
  "routes/content-page.tsx": {
    id: "routes/content-page";
    page: "/dashboard/:workspaceId/env/:envId/pages/:key";
  };
  "routes/assistant.tsx": {
    id: "routes/assistant";
    page: "/dashboard/:workspaceId/assistant";
  };
  "routes/assistant.history.tsx": {
    id: "routes/assistant.history";
    page: "/dashboard/:workspaceId/assistant/history";
  };
  "routes/assistant.ws-token.tsx": {
    id: "routes/assistant.ws-token";
    page: "/dashboard/:workspaceId/assistant/ws-token";
  };
  "routes/share.tsx": {
    id: "routes/share";
    page: "/share";
  };
  "routes/share.view.tsx": {
    id: "routes/share.view";
    page: "/s/:id";
  };
  "routes/invite.tsx": {
    id: "routes/invite";
    page: "/invite/:id";
  };
  "routes/members.tsx": {
    id: "routes/members";
    page: "/orgs/:orgId/members";
  };
  "routes/billing.tsx": {
    id: "routes/billing";
    page: "/orgs/:orgId/billing";
  };
  "routes/domains.tsx": {
    id: "routes/domains";
    page: "/orgs/:orgId/domains";
  };
  "routes/scim.tsx": {
    id: "routes/scim";
    page: "/orgs/:orgId/scim";
  };
  "routes/sso-admin.tsx": {
    id: "routes/sso-admin";
    page: "/orgs/:orgId/sso";
  };
  "routes/saml-admin.tsx": {
    id: "routes/saml-admin";
    page: "/orgs/:orgId/saml";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/login.mfa": typeof import("./app/routes/login.mfa.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/verify-email": typeof import("./app/routes/verify-email.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/account-mfa": typeof import("./app/routes/account-mfa.tsx");
  "routes/api.passkey": typeof import("./app/routes/api.passkey.tsx");
  "routes/api.reveal-token": typeof import("./app/routes/api.reveal-token.tsx");
  "routes/sso.start": typeof import("./app/routes/sso.start.tsx");
  "routes/sso.callback": typeof import("./app/routes/sso.callback.tsx");
  "routes/saml.start": typeof import("./app/routes/saml.start.tsx");
  "routes/saml.acs": typeof import("./app/routes/saml.acs.tsx");
  "routes/oauth.start": typeof import("./app/routes/oauth.start.tsx");
  "routes/oauth.callback": typeof import("./app/routes/oauth.callback.tsx");
  "routes/workspace": typeof import("./app/routes/workspace.tsx");
  "routes/workspace.overview": typeof import("./app/routes/workspace.overview.tsx");
  "routes/workspace.environments": typeof import("./app/routes/workspace.environments.tsx");
  "routes/dashboard.compare": typeof import("./app/routes/dashboard.compare.tsx");
  "routes/dashboard.audit": typeof import("./app/routes/dashboard.audit.tsx");
  "routes/dashboard.notifications": typeof import("./app/routes/dashboard.notifications.tsx");
  "routes/environment": typeof import("./app/routes/environment.tsx");
  "routes/environment._index": typeof import("./app/routes/environment._index.tsx");
  "routes/environment.config": typeof import("./app/routes/environment.config.tsx");
  "routes/environment.flags": typeof import("./app/routes/environment.flags.tsx");
  "routes/environment.secrets": typeof import("./app/routes/environment.secrets.tsx");
  "routes/environment.content": typeof import("./app/routes/environment.content.tsx");
  "routes/environment.keys": typeof import("./app/routes/environment.keys.tsx");
  "routes/content-page": typeof import("./app/routes/content-page.tsx");
  "routes/assistant": typeof import("./app/routes/assistant.tsx");
  "routes/assistant.history": typeof import("./app/routes/assistant.history.tsx");
  "routes/assistant.ws-token": typeof import("./app/routes/assistant.ws-token.tsx");
  "routes/share": typeof import("./app/routes/share.tsx");
  "routes/share.view": typeof import("./app/routes/share.view.tsx");
  "routes/invite": typeof import("./app/routes/invite.tsx");
  "routes/members": typeof import("./app/routes/members.tsx");
  "routes/billing": typeof import("./app/routes/billing.tsx");
  "routes/domains": typeof import("./app/routes/domains.tsx");
  "routes/scim": typeof import("./app/routes/scim.tsx");
  "routes/sso-admin": typeof import("./app/routes/sso-admin.tsx");
  "routes/saml-admin": typeof import("./app/routes/saml-admin.tsx");
};