// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/dashboard/:workspaceId": {
    params: {
      "workspaceId": string;
    };
  };
  "/orgs/:orgId/scim": {
    params: {
      "orgId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/dashboard/:workspaceId" | "/orgs/:orgId/scim";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard/:workspaceId";
  };
  "routes/scim.tsx": {
    id: "routes/scim";
    page: "/orgs/:orgId/scim";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/scim": typeof import("./app/routes/scim.tsx");
};