// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/login/mfa": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/account/mfa": {
    params: {};
  };
  "/api/passkey": {
    params: {};
  };
  "/sso/:orgId/start": {
    params: {
      "orgId": string;
    };
  };
  "/sso/:orgId/callback": {
    params: {
      "orgId": string;
    };
  };
  "/saml/:orgId/start": {
    params: {
      "orgId": string;
    };
  };
  "/saml/:orgId/acs": {
    params: {
      "orgId": string;
    };
  };
  "/oauth/:provider/start": {
    params: {
      "provider": string;
    };
  };
  "/oauth/:provider/callback": {
    params: {
      "provider": string;
    };
  };
  "/dashboard/:workspaceId": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/env/:envId": {
    params: {
      "workspaceId": string;
      "envId": string;
    };
  };
  "/dashboard/:workspaceId/assistant": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/compare": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/audit": {
    params: {
      "workspaceId": string;
    };
  };
  "/dashboard/:workspaceId/notifications": {
    params: {
      "workspaceId": string;
    };
  };
  "/share": {
    params: {};
  };
  "/s/:id": {
    params: {
      "id": string;
    };
  };
  "/invite/:id": {
    params: {
      "id": string;
    };
  };
  "/orgs/:orgId/members": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/billing": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/scim": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/sso": {
    params: {
      "orgId": string;
    };
  };
  "/orgs/:orgId/saml": {
    params: {
      "orgId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/login/mfa" | "/logout" | "/account/mfa" | "/api/passkey" | "/sso/:orgId/start" | "/sso/:orgId/callback" | "/saml/:orgId/start" | "/saml/:orgId/acs" | "/oauth/:provider/start" | "/oauth/:provider/callback" | "/dashboard/:workspaceId" | "/dashboard/:workspaceId/env/:envId" | "/dashboard/:workspaceId/assistant" | "/dashboard/:workspaceId/compare" | "/dashboard/:workspaceId/audit" | "/dashboard/:workspaceId/notifications" | "/share" | "/s/:id" | "/invite/:id" | "/orgs/:orgId/members" | "/orgs/:orgId/billing" | "/orgs/:orgId/scim" | "/orgs/:orgId/sso" | "/orgs/:orgId/saml";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/login.mfa.tsx": {
    id: "routes/login.mfa";
    page: "/login/mfa";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/account-mfa.tsx": {
    id: "routes/account-mfa";
    page: "/account/mfa";
  };
  "routes/api.passkey.tsx": {
    id: "routes/api.passkey";
    page: "/api/passkey";
  };
  "routes/sso.start.tsx": {
    id: "routes/sso.start";
    page: "/sso/:orgId/start";
  };
  "routes/sso.callback.tsx": {
    id: "routes/sso.callback";
    page: "/sso/:orgId/callback";
  };
  "routes/saml.start.tsx": {
    id: "routes/saml.start";
    page: "/saml/:orgId/start";
  };
  "routes/saml.acs.tsx": {
    id: "routes/saml.acs";
    page: "/saml/:orgId/acs";
  };
  "routes/oauth.start.tsx": {
    id: "routes/oauth.start";
    page: "/oauth/:provider/start";
  };
  "routes/oauth.callback.tsx": {
    id: "routes/oauth.callback";
    page: "/oauth/:provider/callback";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard/:workspaceId";
  };
  "routes/environment.tsx": {
    id: "routes/environment";
    page: "/dashboard/:workspaceId/env/:envId";
  };
  "routes/assistant.tsx": {
    id: "routes/assistant";
    page: "/dashboard/:workspaceId/assistant";
  };
  "routes/dashboard.compare.tsx": {
    id: "routes/dashboard.compare";
    page: "/dashboard/:workspaceId/compare";
  };
  "routes/dashboard.audit.tsx": {
    id: "routes/dashboard.audit";
    page: "/dashboard/:workspaceId/audit";
  };
  "routes/dashboard.notifications.tsx": {
    id: "routes/dashboard.notifications";
    page: "/dashboard/:workspaceId/notifications";
  };
  "routes/share.tsx": {
    id: "routes/share";
    page: "/share";
  };
  "routes/share.view.tsx": {
    id: "routes/share.view";
    page: "/s/:id";
  };
  "routes/invite.tsx": {
    id: "routes/invite";
    page: "/invite/:id";
  };
  "routes/members.tsx": {
    id: "routes/members";
    page: "/orgs/:orgId/members";
  };
  "routes/billing.tsx": {
    id: "routes/billing";
    page: "/orgs/:orgId/billing";
  };
  "routes/scim.tsx": {
    id: "routes/scim";
    page: "/orgs/:orgId/scim";
  };
  "routes/sso-admin.tsx": {
    id: "routes/sso-admin";
    page: "/orgs/:orgId/sso";
  };
  "routes/saml-admin.tsx": {
    id: "routes/saml-admin";
    page: "/orgs/:orgId/saml";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/login.mfa": typeof import("./app/routes/login.mfa.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/account-mfa": typeof import("./app/routes/account-mfa.tsx");
  "routes/api.passkey": typeof import("./app/routes/api.passkey.tsx");
  "routes/sso.start": typeof import("./app/routes/sso.start.tsx");
  "routes/sso.callback": typeof import("./app/routes/sso.callback.tsx");
  "routes/saml.start": typeof import("./app/routes/saml.start.tsx");
  "routes/saml.acs": typeof import("./app/routes/saml.acs.tsx");
  "routes/oauth.start": typeof import("./app/routes/oauth.start.tsx");
  "routes/oauth.callback": typeof import("./app/routes/oauth.callback.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/environment": typeof import("./app/routes/environment.tsx");
  "routes/assistant": typeof import("./app/routes/assistant.tsx");
  "routes/dashboard.compare": typeof import("./app/routes/dashboard.compare.tsx");
  "routes/dashboard.audit": typeof import("./app/routes/dashboard.audit.tsx");
  "routes/dashboard.notifications": typeof import("./app/routes/dashboard.notifications.tsx");
  "routes/share": typeof import("./app/routes/share.tsx");
  "routes/share.view": typeof import("./app/routes/share.view.tsx");
  "routes/invite": typeof import("./app/routes/invite.tsx");
  "routes/members": typeof import("./app/routes/members.tsx");
  "routes/billing": typeof import("./app/routes/billing.tsx");
  "routes/scim": typeof import("./app/routes/scim.tsx");
  "routes/sso-admin": typeof import("./app/routes/sso-admin.tsx");
  "routes/saml-admin": typeof import("./app/routes/saml-admin.tsx");
};